src/app/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("main.urls", namespace="main")),
    path("users/", include("users.urls", namespace="users")),
    path("orders/", include("orders.urls", namespace="orders")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [path("__debug__/", include(debug_toolbar.urls))]

src/main/urls.py
from django.urls import path

from main.views import (
    about_view,
    course_detail_view,
    course_list_view,
    courses_search_view,
    home_view,
    load_next_content_view,
    modal_close_view,
    modal_open_contact_view,
    modal_open_demo_view,
)

app_name = "main"

urlpatterns = [
    path("", home_view, name="home"),
    path("about/", about_view, name="about"),
    path("modal-open-demo/", modal_open_demo_view, name="modal-open-demo"),
    path("modal-open-contact/", modal_open_contact_view, name="modal-open-contact"),
    path("modal-close/", modal_close_view, name="modal-close"),
    path("courses/", course_list_view, name="courses-list"),
    path("courses-search/", courses_search_view, name="courses-search"),
    path("courses/<int:course_id>/", course_detail_view, name="course-detail"),
    path(
        "courses/<int:course_id>/load-next/<int:current_block_id>/",
        load_next_content_view,
        name="load-next-content",
    ),
    path(
        "courses/<int:course_id>/load-next/<int:current_block_id>/<int:current_subblock_id>/",
        load_next_content_view,
        name="load-next-content-from-subblock",
    ),
]

src/main/models.py
from typing import Optional

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django_resized import ResizedImageField


class Course(models.Model):
    title = models.CharField(max_length=100, verbose_name="Название курса")
    description = models.TextField(
        blank=True, verbose_name="Описание курса", max_length=250
    )
    price = models.DecimalField(
        max_digits=10, decimal_places=2, default=129.90, verbose_name="Стоимость (RUB)"
    )

    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Дата обновления")

    class Meta:
        verbose_name = "Курс"
        verbose_name_plural = "Курсы"
        ordering = ["-updated_at", "-created_at"]

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        created = self.pk is None
        super().save(*args, **kwargs)
        if created:
            try:
                self.course_profile
            except CourseProfile.DoesNotExist:
                CourseProfile.objects.create(course=self)


class CourseProfile(models.Model):
    course = models.OneToOneField(
        Course,
        on_delete=models.CASCADE,
        related_name="course_profile",
        verbose_name="Профиль курса",
    )
    hours_to_complete = models.PositiveSmallIntegerField(
        default=1,
        validators=[MaxValueValidator(200), MinValueValidator(1)],
        verbose_name="Часов на выполнение",
    )
    number_of_students = models.PositiveIntegerField(
        default=0, verbose_name="Кол-во учеников"
    )
    cover = ResizedImageField(
        size=[854, 480],
        crop=["middle", "center"],
        upload_to="covers/",
        default="covers/default_cover.jpeg",
        verbose_name="Обложка курса",
    )

    class Meta:
        verbose_name = "Профиль курса"
        verbose_name_plural = "Профили курсов"
        ordering = ["-number_of_students"]

    def __str__(self):
        return f"Профиль для курса: {self.course.title}"


class BlockBaseManager(models.Manager):
    def get_max_order(self, filter_fields: Optional[dict] = None):
        filter_fields = filter_fields or {}

        result = self.only("order").filter(**filter_fields).order_by("order").last()
        max_order = result.order
        return max_order

    def do_reordering(self, filter_fields: Optional[dict] = None):
        filter_fields = filter_fields or {}

        course_subblocks = list(
            self.only("order").filter(**filter_fields).order_by("order")
        )
        for index, subblock in enumerate(course_subblocks, 1):
            if subblock.order != index:
                subblock.order = index
        self.bulk_update(course_subblocks, ["order"])


class Block(models.Model):
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="blocks", verbose_name="Курс"
    )
    title = models.CharField(max_length=200, verbose_name="Название блока")
    content = models.TextField(verbose_name="Содержимое блока")
    order = models.PositiveIntegerField(
        default=0,
        verbose_name="Порядок",
    )

    objects = BlockBaseManager()

    class Meta:
        verbose_name = "Блок"
        verbose_name_plural = "Блоки"
        ordering = ["course", "order"]
        unique_together = ("course", "order")

    def __str__(self):
        return f"{self.course.title} - {self.title}"

    def save(self, *args, **kwargs):
        if self.pk is None and self.order is None:
            max_order = Block.objects.get_max_order({"course": self.course})
            self.order = max_order + 1

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        course = self.course
        # For order resetting
        super().delete(*args, **kwargs)

        Block.objects.do_reordering({"course": course})


class SubBlock(models.Model):
    block = models.ForeignKey(
        Block, on_delete=models.CASCADE, related_name="subblocks", verbose_name="Блок"
    )
    title = models.CharField(max_length=200, verbose_name="Название подблока")
    content = models.TextField(verbose_name="Содержимое подблока")
    order = models.PositiveIntegerField(blank=True, verbose_name="Порядок")

    objects = BlockBaseManager()

    class Meta:
        verbose_name = "Подблок"
        verbose_name_plural = "Подблоки"
        ordering = ["block", "order"]
        unique_together = ("block", "order")

    def __str__(self):
        return f"{self.block.title} - {self.title}"

    def save(self, *args, **kwargs):
        if self.pk is None and self.order is None:
            max_order = SubBlock.objects.get_max_order({"block": self.block})
            self.order = max_order + 1

        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        block = self.block
        # For order resetting
        super().delete(*args, **kwargs)

        SubBlock.objects.do_reordering({"block": block})

src/main/forms.py
import re

from django import forms

from app.forms import base_form_class


class EmailForContactForm(forms.Form):
    name = forms.CharField(
        required=True,
        max_length=25,
        label="Имя",
        widget=forms.TextInput(
            attrs={
                "class": base_form_class,
                "placeholder": "Ваше имя",
            }
        ),
    )
    email = forms.EmailField(
        required=True,
        max_length=30,
        label="Email",
        widget=forms.EmailInput(
            attrs={
                "class": base_form_class,
                "placeholder": "example@mail.ru",
            }
        ),
    )
    phone = forms.CharField(
        required=True,
        max_length=20,
        label="Телефон",
        widget=forms.TelInput(
            attrs={
                "class": base_form_class,
                "placeholder": "+99999999999",
            }
        ),
    )
    tg_username = forms.CharField(
        required=True,
        max_length=30,
        label="Ник в Telegram",
        widget=forms.TextInput(
            attrs={
                "class": base_form_class,
                "placeholder": "@telegramnik",
            },
        ),
    )

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if not re.match(r"^\+?1?\d{8,15}$", phone.replace(" ", "")):
            raise forms.ValidationError("Номер формата: +99999999999")
        return phone

    def clean_tg_username(self):
        tg_username = self.cleaned_data.get("tg_username")
        if tg_username.replace(" ", "")[0] != "@":
            raise forms.ValidationError("Нехватает @")
        return tg_username

src/main/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render

from main.decorators import purchase_required
from main.forms import EmailForContactForm
from main.services.fetching import (
    build_next_content,
    get_block,
    get_course_first_content,
    get_courses_by_query,
    get_courses_list,
    get_example_team_members,
    get_next_block,
    get_next_subblock,
)
from main.services.mailing import send_email_for_contact


def home_view(request):
    return render(request, "main/home.html")


def about_view(request):
    team_members = get_example_team_members()
    return render(request, "main/about.html", {"team_members": team_members})


def course_list_view(request):
    """Return all courses"""
    courses = get_courses_list()
    return render(request, "main/course_list.html", {"courses": courses})


def courses_search_view(request):
    """Return searched courses"""
    query = request.GET.get("query", "")
    courses = get_courses_by_query(query)
    return render(
        request,
        "main/partials/partial_search_courses.html",
        {"courses": courses},
    )


@login_required
@purchase_required
def course_detail_view(request, course_id: int):
    """Return first part of course"""

    first_content = get_course_first_content(course_id)
    return render(
        request,
        "main/course_detail.html",
        first_content,
    )


@login_required
@purchase_required
def load_next_content_view(
    request, course_id: int, current_block_id: int, current_subblock_id=None
):
    """Return next part of course"""
    current_block = get_block(current_block_id, only_fields=["order"])

    # Return next subblock if exist
    next_subblock = get_next_subblock(current_block, current_subblock_id)
    if next_subblock:
        next_content = build_next_content(
            next_subblock, "subblock", course_id, current_block_id
        )
        return render(
            request,
            "main/partials/partial_content.html",
            next_content,
        )

    # Return next block if exist
    next_block = get_next_block(current_block, course_id)
    if next_block:
        next_content = build_next_content(next_block, "block", course_id, next_block.id)
        return render(
            request,
            "main/partials/partial_content.html",
            next_content,
        )
    return HttpResponse("")


def modal_open_demo_view(request):
    demo_url = "https://www.youtube.com/embed/u_sIfs7Yom4"
    return render(request, "main/partials/modal_demo.html", {"demo_url": demo_url})


def modal_open_contact_view(request):
    if request.method == "POST":
        form = EmailForContactForm(request.POST)
        if form.is_valid():
            send_email_for_contact(form.cleaned_data)
            return render(request, "main/partials/modal_successful_sending.html")
    else:
        form = EmailForContactForm()
    return render(request, "main/partials/modal_contact.html", {"form": form})


def modal_close_view(request):
    return HttpResponse('<div id="modal"></div>')

src/templates/main/partials/demo_modal_window.html
<div id="modal" class="videoModal toggle" >
    <div class="relative">
        <div class="absolute -top-12 right-0 z-10">
            <button hx-get="{% url 'main:modal-close' %}" hx-target="#modal" hx-swap="outerHTML" hx-trigger="click" class="bg-transparent border border-rose-300 text-rose-300 hover:bg-rose-300/10 font-medium py-2 px-4 rounded-lg transition duration-300 text-lg inline-flex items-center justify-center soft-neon-border">
                <i class="fas fa-times mr-2"></i>
                Close
            </button>
        </div>
        <iframe src="https://www.youtube.com/embed/u_sIfs7Yom4" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
    </div>
</div>

src/templates/main/partials/modal_contact.html
<div id="modal" class="modal-plan relative">
    <div class="absolute top-4 right-4 z-50">
        <button hx-get="{% url 'main:modal-close' %}" hx-target="#modal" hx-swap="outerHTML" hx-trigger="click"  type="button"
                class="close-btn w-10 h-10 bg-slate-800/80 hover:bg-rose-600/90 text-white rounded-full flex items-center justify-center transition duration-300 transform hover:scale-110 soft-neon-border"
                aria-label="Закрыть диалоговое окно">
            <i class="fas fa-times text-lg"></i>
        </button>
    </div>

    <div class="bg-slate-800/95 backdrop-blur-md rounded-2xl p-8 soft-neon-border max-w-md mx-auto">
        <div class="text-center mb-6">
            <h2 class="text-2xl font-bold text-white orbitron-font soft-neon-text mb-2">
                <i class="fas fa-book-open mr-2 text-emerald-300"></i>
                Свяжитесь с нами
            </h2>
        </div>

        <form hx-post="{% url 'main:modal-open-contact' %}" hx-target="#modal" hx-boost="true" hx-include="this" hx-trigger="submit" class="space-y-4">
            {% csrf_token %}

            {% for f in form %}
                {% include 'form_field.html' with field=f %}
            {% endfor %}

            <div class="bg-slate-700/30 rounded-lg p-4">
                <label class="flex items-start">
                    <input type="checkbox"
                           class="mt-1 rounded bg-slate-700 border-slate-600 text-emerald-400 focus:ring-emerald-400 focus:ring-2"
                           value="yes"
                           checked=""
                           aria-required="true">
                    <span class="ml-2 text-sm text-slate-300">
                        Я соглашаюсь на обработку
                        <a href="#" class="text-emerald-300 hover:text-emerald-200 underline">моих персональных данных</a>
                        в соответствии с
                        <a href="#" class="text-emerald-300 hover:text-emerald-200 underline">Условиями и Договором оферты</a>
                    </span>
                </label>
            </div>

            <button type="submit"
                    class="w-full bg-emerald-600 hover:bg-emerald-500 text-white font-bold py-3 px-6 rounded-lg transition duration-300 transform hover:scale-[1.02] soft-neon-glow">
                <i class="fas fa-paper-plane mr-2"></i>
                Отправить заявку
            </button>
        </form>
    </div>
</div>

src/templates/main/partials/modal_demo.html
<div id="modal" class="videoModal toggle" >
    <div class="relative">
        <div class="absolute -top-12 right-0 z-10">
            <button hx-get="{% url 'main:modal-close' %}" hx-target="#modal" hx-swap="outerHTML" hx-trigger="click" class="bg-transparent border border-rose-300 text-rose-300 hover:bg-rose-300/10 font-medium py-2 px-4 rounded-lg transition duration-300 text-lg inline-flex items-center justify-center soft-neon-border">
                <i class="fas fa-times mr-2"></i>
                Close
            </button>
        </div>
        <iframe src="{{ demo_url }}" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
    </div>
</div>

src/templates/main/partials/modal_successful_sending.html
<div id="modal" class="modal-plan relative">
    <div class="absolute top-4 right-4 z-50">
        <button hx-get="{% url 'main:modal-close' %}" hx-target="#modal" hx-swap="outerHTML" hx-trigger="click"  type="button"
                class="close-btn w-10 h-10 bg-slate-800/80 hover:bg-rose-600/90 text-white rounded-full flex items-center justify-center transition duration-300 transform hover:scale-110 soft-neon-border"
                aria-label="Закрыть диалоговое окно">
            <i class="fas fa-times text-lg"></i>
        </button>
    </div>
    <div class="bg-emerald-900/50 border border-emerald-600 rounded-xl p-4 mt-4">
        <div class="flex items-center">
            <i class="fas fa-check-circle text-emerald-300 mr-3"></i>
            <div>
                <p class="text-emerald-300 text-sm">Спасибо! Ваши данные успешно отправлены, ожидайте ответ на указанный контакт от менеджера.</p>
            </div>
        </div>
    </div>
</div>

src/templates/main/partials/partial_content.html
{% load format_text %}
<div id="{{ content_type }}-{{ content.id }}"
    class="mb-6 p-4"
    x-data="{ id: '{{ content_type }}-{{ content.id }}' }"
    x-intersect="activeContent = id"
    x-init="gsap.from($el, { opacity: 0, y: 30, duration: 0.5 })"
    style="opacity: 1 !important;">
    {% if content_type == 'block' %}
        <h2 class="text-lg sm:text-2xl font-semibold text-white mb-3">{{ content.title }}</h2>
        <div class="prose prose-invert text-sm sm:text-base mb-6 p-5 border rounded-lg card-hover soft-fade-in delay-200 visible" style="opacity: 1 !important; overflow-x: auto;">{{ content.content | format_text | safe }}</div>
    {% else %}
        <div class="ml-3 sm:ml-4 mt-2 sm:mt-3">
            <h3 class="text-base sm:text-xl font-medium text-white mb-2">{{ content.title }}</h3>
            <div class="prose prose-invert text-sm sm:text-base mb-6 p-5 bg-gray-800 border border-gray-700 rounded-lg card-hover fade-in delay-300 visible" style="opacity: 1 !important; overflow-x: auto;">{{ content.content | format_text | safe }}</div>
        </div>
    {% endif %}
</div>
{% if next_block_id %}
<div hx-get="{% if next_subblock_id %}
                {% url 'main:load-next-content-from-subblock' course_id=course_id current_block_id=next_block_id current_subblock_id=next_subblock_id %}
              {% else %}
                {% url 'main:load-next-content' course_id=course_id current_block_id=next_block_id %}
              {% endif %}"
     hx-trigger="revealed"
     hx-swap="afterend">
</div>
{% endif %}

src/templates/main/partials/partial_content_list.html
{% load format_text %}
{% for item in contents %}
<div id="{{ item.content_type }}-{{ item.content.id }}"
     x-data="{ id: '{{ item.content_type }}-{{ item.content.id }}' }"
     x-intersect="activeContent = id"
     x-init="gsap.from($el, { opacity: 0, y: 30, duration: 0.5 })"
     style="opacity: 1 !important;">
    {% if item.content_type == 'block' %}
    <h2 class="text-lg sm:text-2xl font-semibold text-white mb-3">{{ item.content.title }}</h2>
    <div class="prose prose-invert text-sm sm:text-base" style="opacity: 1 !important; overflow-x: auto;">{{ item.content.content | format_text | safe }}</div>
    {% else %}
    <div class="ml-3 sm:ml-4 mt-2 sm:mt-3">
        <h3 class="text-base sm:text-xl font-medium text-white mb-2">{{ item.content.title }}</h3>
        <div class="prose  text-sm sm:text-base" style="opacity: 1 !important; overflow-x: auto;">{{ item.content.content | format_text | safe }}</div>
    </div>
    {% endif %}
</div>
{% endfor %}
<script>
    document.addEventListener('DOMContentLoaded', () => {
        const target = document.querySelector('#{{ target_id }}');
        if (target) {
            target.scrollIntoView({ behavior: 'smooth', block: 'start' });
        }
    });
</script>

src/templates/main/partials/partial_search_courses.html
{% load static %}
{% for course in courses %}
    <div class="bg-card bg-card-gradient bg-gray-800 border border-gray-700 rounded-lg overflow-hidden course-card fade-in-delay-200"
         @click="openModal('{{ course.id }}', '{{ course.title|escapejs }}', '{{ course.price }}')">
        <div class="w-full h-60 bg-gray-700 flex items-center justify-center overflow-hidden">
            {% if course.course_profile.cover %}
                <img src="{{ course.course_profile.cover.url }}" alt="{{ course.title }}" class="w-full h-full object-cover">
            {% else %}
                <img src="{% static 'covers/default_cover.jpeg' %}" alt="{{ course.title }}" class="w-full h-full object-cover">
            {% endif %}
        </div>
        <div class="p-6">
            <h3 class="text-xl font-semibold text-white mb-2">{{ course.title }}</h3>
            <p class="text-gray-400 mb-4">{{ course.description|truncatechars:155 }}</p>
            <div class="flex items-center gap-4 text-sm text-gray-400 mb-4">
                <div class="flex items-center gap-1">
                    <i class="fas fa-clock"></i>
                    {{ course.course_profile.hours_to_complete }} часов
                </div>
                <div class="flex items-center gap-1">
                    <i class="fas fa-users"></i>
                    {{ course.course_profile.number_of_students }} студентов
                </div>
            </div>
            <div class="flex justify-between items-center">
                <div>
                    <span class="text-2xl font-bold text-emerald-400">₽{{ course.price }}</span>
                    <span class="text-gray-400 line-through ml-2">₽{{ course.price|add:2500 }}</span>
                </div>
            </div>
        </div>
    </div>
{% empty %}
    <div class="col-span-full text-center py-12">
        <div class="max-w-md mx-auto">
            <div class="text-6xl mb-4 text-gray-400">
                <i class="fas fa-question-circle"></i>
            </div>
            <h3 class="text-xl font-semibold text-slate-400 mb-2">Курсы пока не добавлены</h3>
            <p class="text-gray-400 text-lg mb-6">Мы работаем над созданием новых образовательных программ. Следите за обновлениями!</p>
        </div>
    </div>
{% endfor %}